# ~/.config/yazi/yazi.toml

[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = true

[preview]
max_width = 1000
max_height = 1000

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]

[open]
prepend_rules = [
  { url = "*.{md,lua,toml,yaml,yml,json,sh}", use = "edit" },
]
