require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.lualine"
require "user.indentLine"
-- require "user.diffwiew"
require "user.alpha"
require "user.project"
require "user.whichkey"
require "user.rust-tools"
require "user.fzf-lua"
require "user.dracula"
require "user.bookmarks"

vim.cmd[[colorscheme dracula]]
