# https://github.com/jesseduffield/lazydocker
# Docs: https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md

gui:
  theme:
    activeBorderColor:
      - "#bd93f9"
      - bold
    inactiveBorderColor:
      - "#6272a4"
    selectedLineBgColor:
      - "#44475a"
