#!/usr/bin/env bash
# Regenerate conf/raycast/scripts/sg-pick-pattern.sh from ast-grep-patterns.lua

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/conf/raycast/scripts/sg-pick-pattern.sh"

dropdown=$(ROOT="$ROOT" lua "$ROOT/scripts/gen-raycast-sg-pattern.lua")

cat >"$OUT" <<EOF
#!/bin/bash

# GENERATED by scripts/gen-raycast-sg-pattern.sh — do not edit by hand
# Regenerate: just gen-raycast-sg

# @raycast.schemaVersion 1
# @raycast.title ast-grep pattern
# @raycast.mode silent
# @raycast.packageName Developer Utilities

# @raycast.icon { "source": "file-icon", "fileIcon": "public.shell-script" }

# @raycast.description Copy sg run command for a pattern (dropdown, no fzf).

# @raycast.argument1 { "type": "dropdown", "placeholder": "Pattern", "data": [${dropdown}] }

set -euo pipefail

DOTFILES="\${HOME}/dev/perso/dotfiles"
[[ -f "\$DOTFILES/conf/nvim/lua/ast-grep-patterns.lua" ]] || DOTFILES="\${HOME}/dotfiles"

export LUA_PATH="\$DOTFILES/conf/nvim/lua/?.lua;\$DOTFILES/conf/nvim/lua/?/init.lua;;"

idx="\${1:?}"
read -r pattern lang < <(
  SG_PATTERN_IDX="\$idx" lua -e "
local i = tonumber(os.getenv('SG_PATTERN_IDX'))
local x = require('ast-grep-patterns').patterns[i]
if not x then os.exit(1) end
io.write(x.pattern, '\t', x.lang or 'ts', '\n')
"
)

pat_esc=\${pattern//\'/\'\\\'\'}
cmd="sg run --color=never -p '\$pat_esc' -l \$lang ."

if [[ "\$OSTYPE" == darwin* ]]; then
  printf '%s' "\$cmd" | pbcopy
else
  printf '%s\n' "\$cmd"
  exit 0
fi

echo "Copied: \$cmd"
EOF

chmod +x "$OUT"
echo "Wrote $OUT"
