#!/usr/bin/env bash
# Games / launchers: disable keyd Cmd remap (native Super/Ctrl/Alt for gaming).
# Add WM_CLASS prefixes from: xprop WM_CLASS | tr ',' '\n'
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/conf/keyd/games-classic.conf"

APPS=(
  steam
  Steam
  gamescope
  Gamescope
  cs2
  csgo
  dota2
  wine
  Wine
  proton
  Proton
)

{
  echo "# Generated by scripts/gen-keyd-games-classic.sh"
  echo "# No Super→Ctrl remap while these windows are focused (classic PC keys)."
  echo "# Extend APPS[] in the script, then re-run and redeploy keyd."
  echo
  for app in "${APPS[@]}"; do
    echo "[$app]"
    echo "leftmeta = leftmeta"
    echo "rightmeta = rightmeta"
    echo
  done
} >"$OUT"

echo "Wrote $OUT (${#APPS[@]} apps)"
