#!/usr/bin/env bash
# Generate conf/keyd/gtk-apps.conf — GTK/Electron apps that expect Ctrl+C (not Cmd).
# WezTerm, Cursor, nvim: Super+key passes through as Mac Cmd (see default.conf).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/conf/keyd/gtk-apps.conf"

BINDINGS='a = C-a
b = C-b
c = C-c
d = C-d
e = C-e
f = C-f
g = C-g
h = C-h
i = C-i
j = C-j
k = C-k
l = C-l
n = C-n
o = C-o
p = C-p
q = C-q
r = C-r
s = C-s
t = C-t
u = C-u
v = C-v
w = C-w
x = C-x
y = C-y
z = C-z
/ = C-/
shift-z = C-shift-z
shift-t = C-shift-t
shift-n = C-shift-n
shift-s = C-shift-s
shift-f = C-shift-f
shift-p = C-shift-p
shift-d = C-shift-d
1 = C-1
2 = C-2
3 = C-3
4 = C-4
5 = C-5
6 = C-6
7 = C-7
8 = C-8
9 = C-9'

# WM_CLASS prefixes (keyd prefix match). Add apps with: ./scripts/gen-keyd-gtk-apps.sh
APPS=(
  firefox
  Firefox
  chromium
  google-chrome
  chrome
  obsidian
  Obsidian
  com.obsidian.Obsidian
  org.gnome.Nautilus
  com.slack.Slack
  org.signal.Signal
  org.mozilla.Thunderbird
  com.todoist.Todoist
  com.bitwarden.desktop
  com.getpostman.Postman
)

{
  echo "# Generated by scripts/gen-keyd-gtk-apps.sh — do not edit by hand"
  echo "# Super+letter → Ctrl+letter for Linux GTK/Electron (Cmd+C = copy in browser, etc.)"
  echo
  for app in "${APPS[@]}"; do
    echo "[$app:command]"
    echo "$BINDINGS"
    echo
  done
} >"$OUT"

echo "Wrote $OUT (${#APPS[@]} apps)"
