#!/bin/bash

# GENERATED by scripts/gen-raycast-sg-pattern.sh — do not edit by hand
# Regenerate: just gen-raycast-sg

# @raycast.schemaVersion 1
# @raycast.title ast-grep pattern
# @raycast.mode silent
# @raycast.packageName Developer Utilities

# @raycast.icon { "source": "file-icon", "fileIcon": "public.shell-script" }

# @raycast.description Copy sg run command for a pattern (dropdown, no fzf).

# @raycast.argument1 { "type": "dropdown", "placeholder": "Pattern", "data": [{"title": "console.log (ts)", "value": "1"}, {"title": "import (ts)", "value": "2"}, {"title": "fetch (ts)", "value": "3"}, {"title": "async fn (ts)", "value": "4"}, {"title": "fmt.Println (go)", "value": "5"}, {"title": "errors.New (go)", "value": "6"}, {"title": "context.With (go)", "value": "7"}, {"title": "defer (go)", "value": "8"}, {"title": "go func (go)", "value": "9"}, {"title": "require (lua)", "value": "10"}, {"title": "vim.keymap (lua)", "value": "11"}, {"title": "lazy plugin (lua)", "value": "12"}, {"title": "unwrap (rust)", "value": "13"}, {"title": "println! (rust)", "value": "14"}, {"title": "print (python)", "value": "15"}, {"title": "def (python)", "value": "16"}, {"title": "export (bash)", "value": "17"}] }

set -euo pipefail

DOTFILES="${HOME}/dev/perso/dotfiles"
[[ -f "$DOTFILES/conf/nvim/lua/ast-grep-patterns.lua" ]] || DOTFILES="${HOME}/dotfiles"

export LUA_PATH="$DOTFILES/conf/nvim/lua/?.lua;$DOTFILES/conf/nvim/lua/?/init.lua;;"

idx="${1:?}"
read -r pattern lang < <(
  SG_PATTERN_IDX="$idx" lua -e "
local i = tonumber(os.getenv('SG_PATTERN_IDX'))
local x = require('ast-grep-patterns').patterns[i]
if not x then os.exit(1) end
io.write(x.pattern, '\t', x.lang or 'ts', '\n')
"
)

pat_esc=${pattern//\'/\'\\'\'}
cmd="sg run --color=never -p '$pat_esc' -l $lang ."

if [[ "$OSTYPE" == darwin* ]]; then
  printf '%s' "$cmd" | pbcopy
else
  printf '%s\n' "$cmd"
  exit 0
fi

echo "Copied: $cmd"
