-- https://github.com/folke/which-key.nvim

return {
  "folke/which-key.nvim",
  cond = not vim.g.vscode,
  event = "VeryLazy",
  -- Lazy calls setup(opts) before this; only register :help keymaps here.
  config = function()
    require("which-key").add(require("utils.vim_prefix_help").get_which_key_spec())
  end,
  opts = {
    -- Builtin prefix keys are not auto-triggered; add them so g/z/[… show the preset popup.
    triggers = {
      { " ", mode = "nxso" },
      { "g", mode = "n" },
      { "z", mode = "n" },
      { "[", mode = "n" },
      { "]", mode = "n" },
      { '"', mode = "n" },
      { "'", mode = "n" },
    },
    -- spec order: alphabetical by <leader> suffix for diffs; popup uses `sort` + discovery
    spec = {
      { "<C-S-Tab>", desc = "Previous buffer" },
      { "<C-Tab>", desc = "Next buffer" },
      { "<C-PageUp>", desc = "Previous buffer (terminal fallback)" },
      { "<C-PageDown>", desc = "Next buffer (terminal fallback)" },
      { "<leader>?", desc = "Keymaps (fzf-lua)" },
      { "<leader>H", desc = "Cheatsheets folder (fzf-lua)" },
      { "<leader>K", desc = "Keymaps hub + keyboard-navigation (fzf-lua)" },
      { "<leader>a", group = "ai (avante)", mode = { "n", "v" } },
      { "<leader>c", desc = "Clear search highlight (:noh)" },
      { "<leader>f", group = "grep / ripgrep (fzf-lua)", mode = { "n", "v" } },
      { "<leader>g", group = "git (fzf + lazygit)", mode = { "n", "v" } },
      { "<leader>gb", desc = "Git branches" },
      { "<leader>gc", desc = "Git commits" },
      { "<leader>gf", desc = "Git tracked files" },
      { "<leader>gg", desc = "Git: Lazygit" },
      { "<leader>gs", desc = "Git status" },
      { "<leader>h", group = "git hunks (gitsigns)", mode = { "n", "v" } },
      { "<leader>hb", desc = "Git hunk: blame line" },
      { "<leader>hB", desc = "Git hunk: blame line (full)" },
      { "<leader>hd", desc = "Git hunk: diff this" },
      { "<leader>hn", desc = "Git hunk: next" },
      { "<leader>hN", desc = "Git hunk: previous" },
      { "<leader>hp", desc = "Git hunk: preview" },
      { "<leader>hr", desc = "Git hunk: reset" },
      { "<leader>hR", desc = "Git hunk: reset buffer" },
      { "<leader>hs", desc = "Git hunk: stage" },
      { "<leader>hS", desc = "Git hunk: stage buffer" },
      { "<leader>hu", desc = "Git hunk: undo stage" },
      { "<leader>l", group = "lsp + format", mode = { "n", "v" } },
      { "<leader>la", desc = "LSP code action (fzf-lua)" },
      { "<leader>lg", desc = "Toggle LTeX grammar" },
      { "<leader>o", group = "obsidian", mode = { "n", "v" } },
      { "<leader>p", group = "find files / fd (fzf-lua)", mode = { "n", "v" } },
      { "<leader>q", group = "session (persistence)", mode = { "n", "v" } },
      { "<leader>s", desc = "Document symbols (fzf-lua)" },
      { "<leader>S", desc = "Workspace symbols (fzf-lua)" },
      { "<leader>u", desc = "Undo tree" },
      { "<leader>v", group = "vim commands", mode = { "n", "v" } },
      { "<leader>T", group = "tab pages" },
      { "<leader>Tc", desc = "Close tab" },
      { "<leader>Tn", desc = "New tab" },
      { "<leader>To", desc = "Close other tabs" },
      { "<leader>U", group = "ui floats" },
      { "<leader>Ur", desc = "Refocus float / picker" },
      { "<leader>Ux", desc = "Close all floating windows" },
    },
    -- plugins.presets (operators, motions, g/z, windows) — default on
    sort = { "alphanum", "natural", "group", "local", "order", "mod" },
  },
}
