-- https://github.com/folke/which-key.nvim

return {
  "folke/which-key.nvim",
  cond = not vim.g.vscode,
  event = "VeryLazy",
  -- Lazy calls setup(opts) before this; only register :help keymaps here.
  config = function()
    require("which-key").add(require("utils.vim_prefix_help").get_which_key_spec())
  end,
  opts = {
    -- Popup visibility (minimal): border, padding, opaque float, wider columns.
    win = {
      border = "rounded",
      padding = { 1, 2 },
      title = true,
      title_pos = "center",
      wo = { winblend = 0 },
    },
    layout = {
      width = { min = 26 },
      spacing = 4,
    },
    -- Builtin prefix keys are not auto-triggered; add them so g/z/[… show the preset popup.
    triggers = {
      -- Leader popup: normal only (insert already excluded; visual keeps mappings via timeoutlen).
      { " ", mode = "n" },
      { "g", mode = "n" },
      { "z", mode = "n" },
      { "[", mode = "n" },
      { "]", mode = "n" },
      { '"', mode = "n" },
      { "'", mode = "n" },
    },
    -- spec order: alphabetical by <leader> suffix for diffs; popup uses `sort` + discovery
    spec = {
      { "<C-S-Tab>", desc = "Previous buffer" },
      { "<C-Tab>", desc = "Next buffer" },
      { "<C-PageUp>", desc = "Previous buffer (terminal fallback)" },
      { "<C-PageDown>", desc = "Next buffer (terminal fallback)" },
      { "<leader>?", desc = "Keymaps (fzf-lua)" },
      { "<leader>.", desc = "Repeat last leader action" },
      { "<leader>/", desc = "Search in buffer (fzf-lua, alias)" },
      { "<leader>:", desc = "Command history (fzf-lua)" },
      { "<leader>H", desc = "Cheatsheets folder (fzf-lua)" },
      { "<leader>b", desc = "Buffers (fzf-lua, Ctrl-x delete)" },
      { "<leader>a", group = "ai (avante + cursor-agent)", mode = { "n", "v" } },
      { "<leader>ac", desc = "cursor-agent CLI (vsplit right)" },
      { "<leader>y", group = "yank path" },
      { "<leader>yp", desc = "Yank absolute file path" },
      { "<leader>yr", desc = "Yank relative file path" },
      { "<leader>f", group = "grep / ripgrep / ast-grep (fzf-lua)", mode = { "n", "v" } },
      { "<leader>fs", desc = "ast-grep: pick pattern (cwd)" },
      { "<leader>fS", desc = "ast-grep: pick pattern (file dir)" },
      { "<leader>fc", desc = "ast-grep: type pattern (cwd)" },
      { "<leader>fC", desc = "ast-grep: type pattern (file dir)" },
      { "<leader>f/", desc = "Search in buffer (fzf-lua, alias)" },
      { "<leader>g", group = "git (fzf + neogit + diffview)", mode = { "n", "v" } },
      { "<leader>gb", desc = "Git branches" },
      { "<leader>gc", desc = "Git commits" },
      { "<leader>gC", desc = "Git: Neogit commit popup" },
      { "<leader>gf", desc = "Git tracked files" },
      { "<leader>gg", desc = "Git: Neogit (status)" },
      { "<leader>gl", desc = "Git: Neogit log" },
      { "<leader>gp", desc = "Git: Neogit push" },
      { "<leader>gP", desc = "Git: Neogit pull" },
      { "<leader>gs", desc = "Git status (fzf-lua, quick list)" },
      { "<leader>gd", desc = "Git: Diffview open (edit pane B)" },
      { "<leader>gD", desc = "Git: Diffview file history (LOCAL base)" },
      { "<leader>gx", desc = "Git: Diffview close" },
      { "<leader>h", group = "git hunks (gitsigns)", mode = { "n", "v" } },
      { "<leader>hb", desc = "Git hunk: blame line" },
      { "<leader>hB", desc = "Git hunk: blame line (full)" },
      { "<leader>hd", desc = "Git hunk: diff this" },
      { "<leader>hn", desc = "Git hunk: next" },
      { "<leader>hN", desc = "Git hunk: previous" },
      { "<leader>hp", desc = "Git hunk: preview" },
      { "<leader>hr", desc = "Git hunk: reset" },
      { "<leader>hR", desc = "Git hunk: reset buffer" },
      { "<leader>hs", desc = "Git hunk: stage" },
      { "<leader>hS", desc = "Git hunk: stage buffer" },
      { "<leader>hu", desc = "Git hunk: undo stage" },
      { "<leader>c", group = "test (neotest)" },
      { "<leader>ct", desc = "Test: run nearest" },
      { "<leader>cf", desc = "Test: run file" },
      { "<leader>cS", desc = "Test: run suite" },
      { "<leader>cw", desc = "Test: watch" },
      { "<leader>co", desc = "Test: output" },
      { "<leader>cp", desc = "Test: output panel" },
      { "<leader>cn", desc = "Test: next failure" },
      { "<leader>cN", desc = "Test: prev failure" },
      { "<leader>cy", desc = "Test: summary" },
      { "<leader>cD", desc = "Test: debug nearest (DAP)" },
      { "<leader>d", group = "debug (nvim-dap)" },
      { "<leader>o", group = "tasks (overseer)" },
      { "<leader>or", desc = "Task: run (npm / make / vscode)" },
      { "<leader>ot", desc = "Task: toggle task list" },
      { "<leader>oR", desc = "Task: restart last" },
      { "<leader>db", desc = "Debug: breakpoint" },
      { "<leader>dB", desc = "Debug: conditional breakpoint" },
      { "<leader>dc", desc = "Debug: continue" },
      { "<leader>di", desc = "Debug: step into" },
      { "<leader>do", desc = "Debug: step over" },
      { "<leader>dO", desc = "Debug: step out" },
      { "<leader>dr", desc = "Debug: open REPL" },
      { "<leader>dt", desc = "Debug: terminate" },
      { "<leader>dl", desc = "Debug: re-run last configuration" },
      { "<leader>du", desc = "Debug: UI" },
      { "<leader>e", desc = "Toggle file tree (neo-tree)" },
      { "<leader>E", desc = "Reveal current file in tree" },
      { "<leader>m", group = "marks (harpoon)" },
      { "<leader>ma", desc = "Harpoon: add file" },
      { "<leader>mm", desc = "Harpoon: toggle menu" },
      { "<leader>mn", desc = "Harpoon: next mark" },
      { "<leader>mp", desc = "Harpoon: prev mark" },
      { "<leader>1", desc = "Harpoon: slot 1" },
      { "<leader>2", desc = "Harpoon: slot 2" },
      { "<leader>3", desc = "Harpoon: slot 3" },
      { "<leader>4", desc = "Harpoon: slot 4" },
      { "<leader>5", desc = "Harpoon: slot 5" },
      { "<leader>6", desc = "Harpoon: slot 6" },
      { "<leader>7", desc = "Harpoon: slot 7" },
      { "<leader>8", desc = "Harpoon: slot 8" },
      { "<leader>9", desc = "Harpoon: slot 9" },
      { "<leader>l", group = "lsp + format", mode = { "n", "v" } },
      { "<leader>la", desc = "LSP code action (fzf-lua)" },
      { "<leader>lf", desc = "Format buffer (conform)" },
      { "<leader>lg", desc = "Toggle LTeX grammar" },
      { "<leader>li", desc = "Toggle inlay hints" },
      { "<leader>n", group = "notes (obsidian + markdown)", mode = { "n", "v" } },
      { "<leader>O", desc = "File explorer (oil, floating)" },
      { "<leader>p", group = "find files / fd (fzf-lua)", mode = { "n", "v" } },
      { "<leader>q", desc = "Close buffer (keep window)" },
      { "<leader>Q", desc = "Close buffer + window (force)" },
      { "<leader>qs", desc = "Session: restore (cwd)" },
      { "<leader>qS", desc = "Session: select" },
      { "<leader>ql", desc = "Session: restore last" },
      { "<leader>qd", desc = "Session: stop saving current" },
      { "<leader>r", desc = "Recent files (fzf-lua)" },
      { "<leader>s", desc = "Document symbols (fzf-lua)" },
      { "<leader>S", desc = "Workspace symbols (fzf-lua)" },
      { "<leader>u", group = "diagnostics + ui tools", mode = { "n", "v" } },
      { "<leader>v", group = "vim commands", mode = { "n", "v" } },
      { "<leader>vr", desc = "Registers (fzf-lua, Ctrl-x clear)" },
      { "<leader>vm", desc = "Marks vim (fzf-lua, not harpoon)" },
      { "<leader>T", group = "tab pages" },
      { "<leader>Tc", desc = "Close tab" },
      { "<leader>Tn", desc = "Tab next" },
      { "<leader>Tp", desc = "Tab previous" },
      { "<leader>TN", desc = "New tab" },
      { "<leader>To", desc = "Close other tabs" },
      { "<leader>U", desc = "Undo tree" },
      { "<leader>ud", desc = "Diagnostics (workspace, Trouble)" },
      { "<leader>uD", desc = "Diagnostics (buffer, Trouble)" },
      { "<leader>uc", desc = "Clear search highlight (:noh)" },
      { "<leader>uk", desc = "Toggle keystroke log (analysis)" },
      { "<leader>ur", desc = "Refocus float / picker" },
      { "<leader>ux", desc = "Close all floating windows" },
    },
    plugins = {
      presets = {
        operators = true,
        motions = false,
        text_objects = false,
        windows = true,
        nav = false,
        z = true,
        g = true,
      },
    },
    sort = { "alphanum", "natural", "group", "local", "order", "mod" },
    -- Short delay: popup only in normal (trigger mode=n). Plugin trees show instantly.
    delay = function(ctx)
      return ctx.plugin and 0 or 80
    end,
  },
}
